alias ll="ls -lhA"
alias pf="emu panda flash"
alias controlsd="emu debug controlsd"
alias battery="emu device battery"
alias reboot="emu device reboot"
alias shutdown="emu device shutdown"
alias settings="emu device settings"
